auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
limits_config:
  allow_structured_metadata: false
  
# Use in-memory KV store for single-node ring
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h
